INSERT INTO PRODUTO
(NOME, DESCRICAO, VALOR)
VALUES('Headset', 'Headset Gamer Drives 50mm - 70552', 99.99);
INSERT INTO PRODUTO
(NOME, DESCRICAO, VALOR)
VALUES('Smartphone', 'Smartphone Galaxy, Verde - SM-S901EZGRZTO', 2899.00);
INSERT INTO PRODUTO
(NOME, DESCRICAO, VALOR)
VALUES('Lampada LED Smart', 'Lampada LED Smart, 9W, 810Lm, Branco - 1106139', 29.99);